### ISSUE TITLE
Finetuning an autocompressor model

### ISSUE THREAD

**Issue by imbalu007** [princeton-nlp/AutoCompressors#11]
Hi,
Currently, is it possible to finetune one of the (pretrained) autocompressor models? If yes, could you please provide references to sample code/readme?

**Comment by CodeCreator** [comment]
This should be straightforward!

First, have a look at the [train.sh](https://github.com/princeton-nlp/AutoCompressors/blob/main/run/train.sh) and [train_llama.sh](https://github.com/princeton-nlp/AutoCompressors/blob/main/run/train_llama.sh) scripts in the `run/` folder.  To fine-tune from an existing AutoCommpressor instead of an LM base model, simply change the `model_url` variable to a AutoCompressor on huggingface-hub or from a local checkpoint, e.g., changing [this line](https://github.com/princeton-nlp/AutoCompressors/blob/main/run/train_llama.sh#L57) to `model_url="princeton-nlp/AutoCompressor-Llama-2-7b-6k"` will fine-tune from [this model](https://huggingface.co/princeton-nlp/AutoCompressor-2.7b-6k/).

**Comment by imbalu007** [comment]
Thanks!
Also, I couldn't find references to training/finetuning a tokenizer in the [paper](https://www.cs.princeton.edu/~awettig/autocompressors.pdf). But in the example usage, you refer to a custom tokenizer (I think).
`tokenizer = AutoTokenizer.from_pretrained("princeton-nlp/AutoCompressor-Llama-2-7b-6k")`.
Do we need to finetune the tokenizer also and not just the model?

**Comment by CodeCreator** [comment]
You only need to finetune the model -- the tokenizer remains unchanged, e.g., the tokenizer `princeton-nlp/AutoCompressor-Llama-2-7b-6k` is the same as the standard Llama-2 tokenizer.

**Comment by hxs91** [comment]
@imbalu007 Hi, have you finetuned the AutoCompressor model on downstream task? If so, what about the performance? Thanks.
