### ISSUE TITLE
Held-out perplexity question

### ISSUE THREAD

**Issue by broalantaps** [princeton-nlp/AutoCompressors#16]
Hey bro, how exciting your work is! Thanks for your contribution. I have some confusion surround me：
### The paper mentioned that Perplexity calculated by held-out last 2048 tokens. But it seems that you calculated the entire sequence's nll during the evaluation phase instead of fixing hthe last 2048 tokens. It would be highly appreciated if you could reply me, thanks!

**Comment by AlexChvl** [comment]
Thanks for your question! During evaluation, all metrics are computed with the [`compute_loss()`](https://github.com/princeton-nlp/AutoCompressors/blob/b68a39347ac36fe81bcfdce5bd7c4071387a03d2/substep_trainer.py#L105) function in `subset_trainer.py`. The loss on each segment is logged individually under the `substep_{substep}-seg{i}-nll` metric. When evaluating with different segments, you should compare the losses on the last segment for each configuration. 

Does this answer your question? Otherwise let me know more details of the issue you're facing.

**Comment by broalantaps** [comment]
Thanks for your answer! So you chose the last substep_{substep}-seg{i}-nll and recorded the perplexity, right?

**Comment by AlexChvl** [comment]
Yes, that's right.
